### ISSUE TITLE
[PE-D] Existing decks are lost after crash

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-1/tp#107]
![image.png](https://raw.githubusercontent.com/ng-andre/ped/main/files/ca73f9ab-f15c-4da9-958f-5f7ff4ddeb13.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: ng-andre/ped#2

**Comment by JWweiyin** [comment]
we fixed this with the auto save function.
