### ISSUE TITLE
[PE-D] Error not handled correctly when user inputs 'enter' without index .

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-1/tp#109]
![image.png](https://raw.githubusercontent.com/SvethaMahadevan/ped/main/files/60bc5588-3fc9-4224-a1df-9fb9b97a2c3d.png)

If I just type enter, I get message: For input string: "" . User should probably get an error message. Not sure how to interpret For input string: “”

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: SvethaMahadevan/ped#1

**Comment by JWweiyin** [comment]
fixed already such that user is asked to enter deck index.
