### ISSUE TITLE
[PE-D] Error message seems to be unmatched when trying to enter a blank named deck

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-1/tp#120]
When `enter` is submitted, error message of `For input string: ""` is shown, which doesn't seem to match error expected e.g.) index should be a number.

![image.png](https://raw.githubusercontent.com/pos0414/ped/main/files/70a9cd09-a702-42b4-b2fb-86fffdea9609.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: pos0414/ped#5

**Comment by JWweiyin** [comment]
fixed already so that it says you have to input a deck index.
