### ISSUE TITLE
[PE-D] ‘viewfc' command followed by any string also works although according to UG although command is viewfc.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-1/tp#142]
![image.png](https://raw.githubusercontent.com/SvethaMahadevan/ped/main/files/c855fb41-871b-4b2a-b6c7-40dc9d5f8cb4.png)

‘viewfc randomallrandom’ also works although according to UG although command is viewfc.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: SvethaMahadevan/ped#12

**Comment by JWweiyin** [comment]
we fixed this bug.
