### ISSUE TITLE
[PE-D] 'bye' followed by any string also causes to exit although 'bye' is the command to exit program.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-1/tp#148]
![image.png](https://raw.githubusercontent.com/SvethaMahadevan/ped/main/files/565043dc-a5a0-4c61-bfb1-f5800a375e35.png)

Could do a better validation for the input.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: SvethaMahadevan/ped#13

**Comment by JWweiyin** [comment]
we fixed this.
