### ISSUE TITLE
[PE-D] Error message does not match error for 'edit' command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-1/tp#155]
![image.png](https://raw.githubusercontent.com/SvethaMahadevan/ped/main/files/5e81bc74-194e-4d24-a38a-ee8321d3c0de.png)

A more appropriate error message would be invalid input instead of empty fields.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: SvethaMahadevan/ped#14

**Comment by JWweiyin** [comment]
we think empty fields is actually more specific than invalid input.
