### ISSUE TITLE
[PE-D] Duplicate cards can be added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-1/tp#157]
![image.png](https://raw.githubusercontent.com/ng-andre/ped/main/files/af350bdc-feb2-4f1e-8f58-b2415ec574b8.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ng-andre/ped#12

**Comment by astralum** [comment]
Resolved
