### ISSUE TITLE
[PE-D] Duplicate decks can be added 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-1/tp#160]
Duplicate check is case sensitive when adding new deck 

![image.png](https://raw.githubusercontent.com/ng-andre/ped/main/files/8f55c03e-6ff7-4176-bfed-c6e9d9c58e5e.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ng-andre/ped#13

**Comment by JWweiyin** [comment]
this is not a bug.
