### ISSUE TITLE
Code Review for @ThaddeusLim99

### ISSUE THREAD

**Issue by shivin9** [AY2122S1-CS2113T-F12-1/tp#170]
![image](https://user-images.githubusercontent.com/13609964/139646210-56f7158c-2e29-4f65-bf53-f6449b85d51a.png)
![image](https://user-images.githubusercontent.com/13609964/139646236-59ef00b4-4522-4cfe-860d-cec116da7ee9.png)

Any explanation for line 80?

**Comment by ThaddeusLim99** [comment]
It is just a comment on what the move command format should be like. Will remove it for the final submission
