### ISSUE TITLE
v1.0 CardLI

### ISSUE THREAD

**Issue by xRossKoh** [AY2122S1-CS2113T-F12-1/tp#6]
Week 7 tp task delegations based on user stories

Wei Yin: Implement add function as per user story 1 - As a user, I can add flashcards.
Xing Kai: Implement delete function as per user story 2 - As a user, I can delete flashcards.
Min Yue: Implement view function as per user story 3 - As a user, I can view my flashcards. 
Thaddeus: Implement test function as per user story 4 - As a user, I can test myself with my flashcards.
Kenneth: Implement error detection as per user story 5 - As a student preparing for their exam, I can see a list of the flashcards I got wrong so that I know which concepts I do not know.

As per our discussion, we will implement our individual parts based on the FlashCard class that can be pulled from this repo. Ideally, we will implement a FlashCardManager class to keep track of all the flashcards, and each individual function should be implemented within the aforementioned class. If you wish to use a different implementation, please explain the new implementation in detail when submitting a pull request for review, and we can discuss it together as a team.

**Comment by shivin9** [comment]
Looks good to me.
You can use the Issue Tracker itself to keep track of conversations regarding the project also.

**Comment by xRossKoh** [comment]
All v1.0 functionalities have been implemented and pushed to team repo.
